### ISSUE TITLE
Tenability Calculation Odd Results

### ISSUE THREAD

**Issue by ahmedsalem70** [firemodels/cfast#1256]
[Case A.zip](https://github.com/firemodels/cfast/files/3168925/Case.A.zip)

I tried to estimate the FED using CFAST by applying a target at a certain location of concern, but the results were confusing as the FED gas were of the order of 10,000.

Attached is a copy of the input file of the test case.

**Comment by rpeacoc** [comment]
I think it's related to your chemical formula.  CFAST assumes that all nitrogen in the fuel is converted to HCN.  In reality, a very small fraction is actually converted to HCN and the rest goes back to elemental nitrogen.  We are working to include this in the code, but for now you have to adjust the nitrogen in the chemical formula in the input by hand.  Typical conversion rates are in the 0.1 % to 10 % range. There's a paper in the 2008 IAFSS proceedings by Purser and Purser that presents some data.

Nearly all of your tenability is coming from HCN.  In the last five minutes of your simulation, the CO FED increment is about 0.8 and the HCN more than 20000.

**Comment by ahmedsalem70** [comment]
Thank you so much for your reply. 
I tried to change the Nitrogen content by making it 0 instead of 1. The result showed FED Gas of no more than 9 at the end of the simulation, while the FED Heat still showing results with an order of magnitude of 3. Attached is the input file of the test case.
[Case A (2).zip](https://github.com/firemodels/cfast/files/3193017/Case.A.2.zip)

**Comment by rpeacoc** [comment]
The results without HCN don't seem unrealistic to me.  The fire compartment gets very hot and hence a very high FED for heat.  Toxic gases are in the single digits with the first one reaching unity in about 200 s for the fire room.  Some of the excessive heat comes from pressure effects since your structure is hermetically sealed, but it still would get very hot from the fire.  Typical limits for temperature are on the order of 100 C for a few minutes.  The fire compartment exceeds that by a lot.

Thoughts?

**Comment by ahmedsalem70** [comment]
I will make a tiny opening at the end of corridor 3 to the outside with a soffit height of 10 cm and see what will happen.

**Comment by ahmedsalem70** [comment]
Even with a 20 cm high opening the FED for Heat still of the order of 4 digits. Any suggestions?

**Comment by rpeacoc** [comment]
If you look at the heat FED and only look at the peak 60 s, you g et an FED more than 1200.
