### ISSUE TITLE
Mechanical Ventilation

### ISSUE THREAD

**Issue by ahmedsalem70** [firemodels/cfast#1264]
Hi There,
This is the first time to use the Mechanical Ventilation tool in CFAST. I would like to be sure that I am using this feature in the right way. Is there any tutorial that explains how to use this feature to create smoke extractor fans and supply air fans?

**Comment by ahmedsalem70** [comment]
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan1' COMP_IDS = 'Corridor 1', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 1.5, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan2' COMP_IDS = 'Corridor 1', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 11.5, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan3' COMP_IDS = 'Corridor 1', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 21.5, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan4' COMP_IDS = 'Corridor 1', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 31.5, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan5' COMP_IDS = 'Corridor 2', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 3.6, 0.8
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Smoke Extraction-Fan6' COMP_IDS = 'Corridor 3', 'OUTSIDE'
      AREAS = 0.25, 0.25 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.25 CUTOFFS = 200, 300 OFFSETS = 3.6, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'Supply Air' COMP_IDS = 'OUTSIDE', 'Corridor 3'
      AREAS = 0.25, 0.25 HEIGHTS = 0.55, 0.55 FLOW = 1.5 CUTOFFS = 200, 300 OFFSETS = 7.2, 0.5
      CRITERION = 'TIME' T = 0, 42, 600 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 /

**Comment by ahmedsalem70** [comment]
I used the above mechanical ventilation configuration to simulate 6 extraction fans and one supply air fan. The problem is that the oxygen concentration drops to zero in the entire domain (not just the room of fire origin) for no reason.

**Comment by preneke** [comment]
Can you attach the input file for the whole case so that we can reproduce the problem?

**Comment by ahmedsalem70** [comment]
[Case C.zip](https://github.com/firemodels/cfast/files/3276986/Case.C.zip)

**Comment by rpeacoc** [comment]
I'm actually surprised the case works as well as it does. Usually with mechanical ventilation, you have to have some kind of natural vent leakage to the outside to relieve the pressure.  

What's happening is that the fire is large enough that the supply air is not sufficient to burn all of the fuel.  This results in additional burning in the upper layers of the rooms to consume the rest of the fuel. Since the ventilation system is only removing are from the upper layer and supplying it to the lower layer, the oxygen level in the upper layer of rooms where there is upper layer burning goes down as the fuel is burned.


A few thoughts on the test case: 1) the room you seem to have added inside the fire room does not take away from the volume of the fire room; it's really only there for visualization. If you really want an L-shaped compartment, it needs to be modeled as two compartments connected by vents.  2) Is the space really perfectly sealed or is there some leakage that would occur? If so, you can add additional natural flow vents to simulate the leakage. 3) Values chosen for the mechanical ventilation cutoff (which defaults to shutting off between 200 and 300 Pa) would impact you case since at the moment, your scenario results in a compartment pressure of about 250 Pa.  This means that some of the vents are not supplying the full flow due to being in the middle of the cutoff range. Unfortunately, there is little data available to make intelligent choices for these inputs without detailed data about the fan system.

**Comment by ahmedsalem70** [comment]
Thank you so much for your detailed reply. Actually, I am simulating this test case on both CFAST and FDS. The configuration of the test case is similar to a cabin connected to a series of corridors aboard an existing Nile-floating hotel. The fire load is typical for cabin fires aboard similar ships. The inside room is representing a closed toilet inside the main cabin. The proposed mechanical ventilation system has six smoke extractors distributed along the three corridors with one supply air fan at the rear end of the last corridor. The same scenario has been simulated in FDS and the results were as expected without showing zero oxygen concentration or incomplete combustion inside the room of fire origin. Any suggestions?

**Comment by ahmedsalem70** [comment]
Regarding your thoughts about the test case:
1) I will change the room to be L-shaped as you pointed in your reply and see the difference.
2) The compartments are totally enclosed and there is no chance for leakage to outside.
3) I tried to change the cutoff values several times (300 and 400 Pa, 350 and 450 Pa) but I have noticed that the pressure inside the domain starts to increase to values close to those specified as ventilation cutoff.

**Comment by rpeacoc** [comment]
Both the mechanical ventilation and combustion chemistry in CFAST are very simple compared to FDS. Mixing within compartments due to the high ventilation rate and localized combustion are modeled in detail in FDS. In CFAST, there is no mixing of layers within a compartment; with only limited mixing at vents. Combustion is a simple chemical balance in CFAST. In FDS, oxygen availability and combustion is determined locally within each cell of the calculation.

The more detailed modeling in FDS naturally leads to more detailed results, particularly in sealed compartments with significant mechanical ventilation. I think this is why you are seeing different results.

The “visually inserted” compartment inside the fire has no effect on the results for CFAST. Unlike FDS, there is no such thing as a blockage. Compartments in CFAST are completely distinct control volumes only connected at vents. Placement of compartments in relation to one another has no impact on the simulation results.
