### ISSUE TITLE
Vent fraction

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1372]
Potential issues noted with attached input file:

Wall Vent 'door' is set with an opening fraction of 0 at all times in Cedit, and defined in the .in with F=0,0, and the .out file indicates that RAMP#1 has 0 opening fraction at all times. However, the opening has flows at all times, and is reported in the .f.out file with an opening fraction of 1.0 at all times. 

[VentCloseFraction.zip](https://github.com/firemodels/cfast/files/3927138/VentCloseFraction.zip)

**Comment by rpeacoc** [comment]
Thanks. I'll take a look.

**Comment by rpeacoc** [comment]
The wall vent 'door' was specified with the OUTSIDE as the first compartment and Comp 1 as the second compartment.  If you switch these so that Comp 1 is the first compartment, it works fine. 

The problem was that CFAST automatically recognizes the issue and swaps the compartments for the vent flow calculation but not for the open/close calculation. That's a bug in the code

 We'll add a check in CEdit to flag this as an error and fix CFAST to swap the order of the compartments (which it does now) and its associated open and close RAMP (which it doesn't do now).

For now, the workaround is to insure the "inside" is always the first compartment in vent flow specifications.
