### ISSUE TITLE
Target fails to converge with very high gas temeperatures - CFAST 7.5.0

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#1439]
How to keep wall vent closed during the entire simulation time? 
There is a parameter in Cedit - initial open, however it is not accessible. 
Definition by: CRITERION = 'TIME' T=0 F=0 causes error:
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
CRITERION = 'TIME' T=0, 10 F=0,0 causes same problem.

It seems no reason to place closed doors. However, I perform Monte Carlo simulations and the doors open/close position is drawn from a distribution.

**Comment by rpeacoc** [comment]
I can't replicate your problem with my version of 7.5.0. Try the one here:

https://drive.google.com/open?id=173ZQJ0FSvqp82X8nfEwQfEBBnBXDZtj5

It should be newer than the one you are using.  If you have any leaks specified, you'll have to manually edit the file to change LEAK_AREA to LEAK_AREA_RATIO for an existing file to work. 

If you have any ceiling/floor vents or mechanical vents, check to make sure the namelist inputs for them have the required / at the end of the last input line for each of the inputs. This was an error in the original pre-release version.

If none of that works, can you upload an input file that fails?

**Comment by akrasuski** [comment]
I'm using Linux version - gnu_linux_64 - compiled.
[c1.txt](https://github.com/firemodels/cfast/files/4481125/c1.txt)

**Comment by rpeacoc** [comment]
I have a few thoughts. 1) It's actually failing in the target routine because the temperatures are so high.  2) With a large fire in an unvented space with adiabatic surfaces, the temperature and pressures are getting to unrealistic levels with temperature above 1300 C and pressures about 500000 Pa. 2) You've specified an internal temperature depth of 0.5 m in a material that's only 0.016 m thick.

I'll continue to look to see if there's something we can do so the model doesn't fail so rudely.

**Comment by rpeacoc** [comment]
The problem is that with the extreme conditions, CFAST is taking too long a timestep for the solution of the target temperature to converge.  It happens both on linux and Windows, but the Windows version doesn't throw an error; it just sets the result to NaN which then becomes a bad guess for the equation solver.  On linux, the program stops.

If you set the timestep to a smaller than default value, the model runs fine.  I tried 0.01 s, but larger values may work.  We'll work to have CFAST better determine the appropriate maximum timestep for targets.

**Comment by rpeacoc** [comment]
Here's a test case that fails trying to calculate the target temperature, setting target flux to Nan on Intel Windows and failing with a floating point overflow on Linux. The problem is the time step is too large to calculate the heat transfer through the target. Setting the maximum time step to 0.01 s (add `MAX_TIME_STEP = 0.01` to the `&MISC` line) instead of the default maximum of 2 s allows the simulation to run.

```
&HEAD VERSION = 7500, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 3600 PRINT = 60 SMOKEVIEW = 15 SPREADSHEET = 15 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Material Properties 
&MATL ID = 'NM 1' MATERIAL = 'New Material 1', 
      CONDUCTIVITY = 0.16 DENSITY = 790 SPECIFIC_HEAT = 0.9, THICKNESS = 0.016 EMISSIVITY = 0.9 /
 
!! Compartments 
&COMP ID = 'C1'
      DEPTH = 2.4 HEIGHT = 2.4 WIDTH = 3.6 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 /
&COMP ID = 'C2'
      DEPTH = 2.4 HEIGHT = 2.4 WIDTH = 3.6 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 3.6, 0, 0 GRID = 50, 50, 50 /
 
!! Wall Vents
&VENT TYPE = 'WALL' ID = 'WallVent_1' COMP_IDS = 'C1', 'C2' TOP = 2, BOTTOM = 0, WIDTH = 1
  FACE = 'RIGHT' OFFSET = 1.3 /
&VENT TYPE = 'WALL' ID = 'WallVent_2' COMP_IDS = 'C1' 'OUTSIDE'  TOP = 2, BOTTOM = 0, WIDTH = 1
  CRITERION = 'TIME' T = 0, 0 F = 0, 0 FACE = 'FRONT' OFFSET = 1.3 /
 
!! Fires 
&FIRE ID = 'New Fire 1'  COMP_ID = 'C1', FIRE_ID = 'New Fire 1'  LOCATION = 1.8, 1.2 / 
&CHEM ID = 'New Fire 1' CARBON = 1 CHLORINE = 0 HYDROGEN = 4 NITROGEN = 0 OXYGEN = 0 HEAT_OF_COMBUSTION = 50000 RADIATIVE_FRACTION = 0.35 / 
&TABL ID = 'New Fire 1' LABELS = 'TIME', 'HRR' , 'HEIGHT' , 'AREA' , 'CO_YIELD' , 'SOOT_YIELD' , 'HCN_YIELD' , 'HCL_YIELD' , 'TRACE_YIELD'  /
&TABL ID = 'New Fire 1', DATA = 0, 0, 0, 0.001, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 30, 10.54, 0, 0.01881082, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 60, 42.16, 0, 0.05702374, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 90, 94.86, 0, 0.1090942, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 120, 168.64, 0, 0.1728637, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 150, 263.5, 0, 0.2470357, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 180, 379.44, 0, 0.3307118, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 210, 516.46, 0, 0.4232185, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 240, 674.56, 0, 0.5240247, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 270, 853.74, 0, 0.6326969, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 300, 1054, 0, 0.7488722, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 600, 1054, 0, 0.7488722, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 630, 853.74, 0, 0.6326969, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 660, 674.56, 0, 0.5240247, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 690, 516.46, 0, 0.4232185, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 720, 379.44, 0, 0.3307118, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 750, 263.5, 0, 0.2470357, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 780, 168.64, 0, 0.1728637, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 810, 94.86, 0, 0.1090942, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 840, 42.16, 0, 0.05702374, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 870, 10.54, 0, 0.01881082, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 900, 0, 0, 0, 0.01, 0.01, 0, 0, 0 /
&TABL ID = 'New Fire 1', DATA = 910, 0, 0, 0.09, 0.01, 0.01, 0, 0, 0 /
 
!! Devices
&DEVC ID = 'Targ 1' COMP_ID = 'C1' LOCATION = 1.8, 1.2, 0 TYPE = 'PLATE' MATL_ID = 'NM 1'  NORMAL = 0, 0, 1 TEMPERATURE_DEPTH = 0.008 DEPTH_UNITS = 'M' /
 
&TAIL /
```

**Comment by akrasuski** [comment]
Thank you very much for your help. Any way, such a definition of closed door should be correct in most cases:
CRITERION = 'TIME' T = 0, 0 F = 0, 0
or it is enough to set: 
CRITERION = 'TIME' T = 0 F = 0
?

**Comment by rpeacoc** [comment]
I believe either will work. Personally when I do one that is always closed, I do something like T=0,1 F=0,0

**Comment by akrasuski** [comment]
Thank you very much for your help.

**Comment by rpeacoc** [comment]
It’s a test case that fails trying to calculate the target temperature because the time step is too large.  I know you calculate a maximum iteration for wall conduction based on the thermal penetration depth and assume there would a comparable one for targets now that we only do an explicit solution.  Can you take a look, oh master of heat conduction, and see if we can add an initialization step for targets that would lower the maximum time step if needed.
