### ISSUE TITLE
Data files for validation cases

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1621]
Where are the data files for the validation cases? They were located in a subdirectory off the Validation\"TestSeries" folders, but starting about V7.3.0 these subdirectories are no longer present.

**Comment by rmcdermo** [comment]
You mean this?
https://github.com/firemodels/cfast/tree/master/Validation

**Comment by SPHunt** [comment]
Yes, but the experimental data files are not provided, these are just the input files. Github mirrors for older CFAST versions have a subfolder with the experimental data, which is needed to do the results comparison.

**Comment by SPHunt** [comment]
Note there are newer test series added, since the last CFAST version with the experimental data folders on the github mirror

**Comment by rmcdermo** [comment]
Ah, sorry, try this:
https://github.com/firemodels/exp

At some point we unified the FDS and CFAST experimental data.

**Comment by SPHunt** [comment]
That's what I was looking for, thanks for quick resolution.

**Comment by rmcdermo** [comment]
We did not want to track two repositories with the same data because the data was being reviewed and updated.  The formal Git way to handle this is with [Submodules](https://github.com/firemodels/fds/wiki/Git-Notes-Submodules), but this can be complicated for the users.  We opted to use a new repo and simply agree on a common directory structure within the post processing scripts.  If this work, please go ahead and close the issue.  Thanks
