### ISSUE TITLE
Incident heat flux for device near flames

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1683]
(Version 7.5.2) The incident heat flux for a device located near (or within) the fire plume seems to zero out. See incident heat flux for device 'TARG 1' generated with attached input file. 

[MCC-TC_Issue.zip](https://github.com/firemodels/cfast/files/5691689/MCC-TC_Issue.zip)

**Comment by rmcdermo** [comment]
Thanks, we will take a look.

**Comment by preneke** [comment]
Sean,
 
Congratulations, you have hit the unlucky jackpot. If you move your detector 1 mm higher you won’t have a problem.
 
What happened is that in the point source calculation for the fire radiation, the point source is set at 1/3 of the flame height above the xy center of the fire UNLESS the distance from the base of the fire to the ceiling is less than the flame height. In that case then the point source is 1/3 the distance from the base of the fire to the ceiling. In your case the base of the fire is 2.4 m high, the ceiling is 3 m so when the flame height exceeds 0.6 m the point source is set to 2.6 m at the x,y location of fire. That just happens to be exactly where the target is. CFAST currently calculates that there is no flux from the fire to a target in that situation. We thank you for your unfortunate luck but it is not clear what the best solution should be so it maybe a while before we have a version of CFAST that appropriately addresses the problem. We’ll work on it and on a simple verification exercise for the details of target heat transfer.
 
While there is a work around and we are working on a fix there is the issue of whether a zone model is appropriate for this problem. The issue is that CFAST models the effects of a fire on a structure. It doesn’t actually model the fire so the assumptions about what is going on in and near the fire are very rudimentary. There may not be a better model to calculate an answer for your problem but it is important to keep in mind that you may be  pushing CFAST beyond the range of cases where it has been validated.
 
Hope this helps.
 
Paul

**Comment by SPHunt** [comment]
Paul, thanks for identifying the issue. While a lucky jackpot is preferred, I recognize the output data is probably not ideal for CFAST. This is actually part of an effort to update NUREG-1934, where we look at a range of model tools applied to the same problem and assess how each performs. In this case, it makes sense to make note of the TC is located within the flame zone and indicate that the validation basis for CFAST is not strong for this region.

**Comment by rpeacoc** [comment]
Thanks Sean.  We'll update the code to avoid the odd drop to zero by ensuring that the cosine doesn't go to zero.

**Comment by rpeacoc** [comment]
No change in V&V results with this fix. If you are interested, I can make a pre-release copy of CFAST available for you to work with.

**Comment by SPHunt** [comment]
Thanks for addressing. If possible, we would be interested in trying out the pre-release copy on the cases we are working with. Can you make available a link for this?

**Comment by rpeacoc** [comment]
Sorry, Sean.  I just saw this.  Here's a link.  The release version should be out within a day or so.

https://drive.google.com/file/d/1g8Re2hGvRbLEDHz_eu7ORCXmchJQdtiV/view?usp=sharing
