### ISSUE TITLE
Density trend, no leakage, no ventilation, adiabatic compartment surfaces.

### ISSUE THREAD

**Issue by Dylan-I** [firemodels/cfast#1893]
Hello all

I have a question regarding the density trend of the data of my experiment.

I'm doing a very simple experiment to get a grasp of CFAST.
The fuel used is propane.
The inputted HRR can be found in the Excel sheet and the mathematical description can be found in the HRR picture.
The compartment is 1.5m x 1.25m x 1m.

The pressure and temperature profiles are as expected.
The density profile is not as expected.
The density lowers although no mass is released from the compartment, only added in the form of propane fuel.

The integral of the HRR shows that ±36.13 grams of propane is added to the compartment during the experiment.
I expected an increase of 0.02 kg/m³ in density not a decrease of ±0.000135kg/m³.

What am I missing here?

Thank you.
Kind regards Dylan.

Generated data.
[CFAST_TEST0_ADIABATIC.xlsx](https://github.com/firemodels/cfast/files/6434462/CFAST_TEST0_ADIABATIC.xlsx)

Information
[HRR.xlsx](https://github.com/firemodels/cfast/files/6434380/HRR.xlsx)
![1](https://user-images.githubusercontent.com/74604389/117296843-cede1680-ae75-11eb-85c4-289fa21f368a.png)
![2](https://user-images.githubusercontent.com/74604389/117296894-dc939c00-ae75-11eb-8087-df63f31ece6c.png)
![3](https://user-images.githubusercontent.com/74604389/117296990-f92fd400-ae75-11eb-9c2a-d77d69fc99ab.png)
![HRR](https://user-images.githubusercontent.com/74604389/117297026-00ef7880-ae76-11eb-8e0f-40891a305dc5.png)
![Pressure](https://user-images.githubusercontent.com/74604389/117297038-0482ff80-ae76-11eb-9f95-4846796b12a8.png)
![Temperature](https://user-images.githubusercontent.com/74604389/117297045-077df000-ae76-11eb-815b-d18d2c992c80.png)
![Density](https://user-images.githubusercontent.com/74604389/117297057-0b117700-ae76-11eb-9642-6f997ead80d2.png)

**Comment by rpeacoc** [comment]
Can you attach your input file so we can run the scenario and look at all the output files?

**Comment by Dylan-I** [comment]
Hello, I would like to but the website doesn't allow me to upload a '.in' file?
I changed the file extension to '.txt' maybe if you swap it back it still works.

[NYX_TEST0.txt](https://github.com/firemodels/cfast/files/6435826/NYX_TEST0.txt)

**Comment by rpeacoc** [comment]
It looks like you are getting the density from the _zone.csv file, Is that correct?  That file is used internally by CFAST for communicating to smokeview and may not be in a form that's usable by the user.

**Comment by Dylan-I** [comment]
Yes, correct. Good to know, thank you. 
It's a bit unclear for me what the exact output is from the CFAST program.
What I see as relevant outputs are:
The temperature and the pressure shown at the end of the simulation or found in the '_compartments' file. (peak values)
And the smokeview visualization.
Correct? 
All other data is only used for the simulation and is not directly usable or representative for what is going on in the compartment?
Is there any way for me to look at the source code of the program, the Fortran or C++ code where the mathematical relations would be found?

**Comment by rpeacoc** [comment]
All the manuals are available at https://github.com/firemodels/cfast/releases/tag/CFAST7.6.0. The Technical Reference Guide describes the model in detail with an appendix that derives the differential equations that are used. Also, particularly relevant to your case are two examples in the Validation Guide in sections 3.1.4 and 3.2.1. If I work out the mass balance for your cases, it's accurate to within about 1 part in 10^6 which is the set tolerance for the equation solver.

Of course, since you do have a fire in the compartment, some of the oxygen mass is consumed in the combustion to produced the CO2 and water.  The N2 and initial H2O are not involved in the chemical reaction so they just are carried along as part of the bookkeeping.

All the source code for the model is available in the online repository for the model at https://github.com/firemodels/cfast

The temperature and pressure are shown in the _compartments.csv file, Details of gas species are also in the _compartments.csv file.  

The _masses.csv file has the total mass of different species in the control volumes in a test cases. 

The _vents.csv would have details of flow through vents (which you don't have in your scenario). The _walls.csv has temperatures of the compartment surfaces. 

The _devices.csv would have details of detectors and sprinklers (which you don't have in your scenario).

**Comment by rpeacoc** [comment]
We'll close this for now.  If you have additional issues with the code, feel free to submit a new issue
