### ISSUE TITLE
Sprinklers - Temperature Evoluation

### ISSUE THREAD

**Issue by eccordeiro** [firemodels/cfast#1928]
Hello,
I'm creating a room with a fire load and it's protected by sprinklers. When I run the simulation after activaiotn of the sprinkler the temperature continues to rise. I verified in the manual that CFAST only calculates the heat release rate rate. It would be possible to explain why the cooling that water will cause in the behavior of the fire is not considered.

Thank you very much,
Elisabete

**Comment by preneke** [comment]
Hello Elisabette, 
I wish I had a better answer then this but the reason the cooling from the sprinkler spray isn't included is because there is no model of that for zone fire models. It is a very localized phenomena with lots of parameters such as droplet size distribution, distribution of droplets in room and so on. There also isn't a lot of experimental data to use to develop a model. I don't believe there are any zone models that attempt to account for this cooling. The best I can do is point you to FDS. 

I am sorry I don't have a better answer for you but I hope this helps. 

Paul

**Comment by eccordeiro** [comment]
Hello Paul, 
Thank you for the answer.
