### ISSUE TITLE
New tool graphing input of the building geometry

### ISSUE THREAD

**Issue by bvchirkov** [firemodels/cfast#1950]
Hello!

I use CFAST when teaching master students at Udmurt State University (Russian Federation, Izhevsk).

Entering the geometry of a large building through CEdit is very difficult. That's why I wrote a plugin for Inkscape - 
https://github.com/bvchirkov/cfast-inkex.

I would be glad if it makes someone's job easier.

**Comment by rmcdermo** [comment]
@bvchirkov Thanks.  This is interesting.  However, I'm a bit worried because some of the installation instructions and messages in the GUI are in Russian.  Another small issue is that we, as of yet, do not have a Third-Party Tools wiki for CFAST similar to what we have for FDS.  It would not be too much trouble to start one, or to add this to the FDS wiki.  However, I'd like to see the language issues sorted first.  In the meantime, I suggest you post this to the [CFAST discussion forum](https://groups.google.com/g/cfast).  Thanks

**Comment by bvchirkov** [comment]
Thank you. In the near future I will be translating the GUI and documentation.
Also submitted a request to the CFAST discussion forum.
