### ISSUE TITLE
CFAST Versions Produce Vastly Different ULTs

### ISSUE THREAD

**Issue by dmmcmahon-lanl** [firemodels/cfast#2053]
Hello,
We are migrating models that were originally built in CFAST 5.1. 

Nothing in the model itself has changed, the fires have the same HRR, compartments, materials etc.

CFAST 7.1.1 gives upper layer temperatures that are about half as large as those obtained when running CFAST 5.1.

Is this to be expected? 

Does anyone know if there are any modifications that have been made to CFAST in the interim that could lead to the difference? CFAST 7.7.1 produces similar results to 7.1.1. 

Thanks,
David

**Comment by rpeacoc** [comment]
In some versions of CFAST 5, the heat release of the fire was, incorrectly, counted twice. This was fixed around version 6.1.1 as part of a complete rewrite of the combustion / kinetics routines. The problem did not exist in earlier versions of the model. For this reason, we don't recommend the use of version 5. Version 6 and later versions are routinely compared to verification testing (where analytic solutions exist) and validation tests (with available experimental data) Thus, for newer versions, we can make quantitative statements of the accuracy of the model. This is documented in the V&V guide for each version of the model.

Exact details of the error and its fix are unfortunately no longer available since version 5 is nearly 20 years old at this point.
