### ISSUE TITLE
Extremely High Target Heat FED 

### ISSUE THREAD

**Issue by omarroq** [firemodels/cfast#2055]
Hello! 

I am currently running simulations with the goal of conducting tenability assessments at different compartments. An issue I have been encountering is that the Target Heat FED quickly increases and eventually reaches around 9000. I would appreciate any guidance and/or clarification on why this occurs.

I have attached the input file below.

Thank you. 

[HighFED.zip](https://github.com/firemodels/cfast/files/11912537/HighFED.zip)

**Comment by preneke** [comment]
I can verify that 187.3 s into the simulation, for no apparent reason, increases massively. I will take a look into this.

Paul

**Comment by preneke** [comment]
Your values for the "Human" target do not seem correct. I can't provide you with correct values but you should check them. I would also strongly suggest you use a much thicker target. I am assuming you are interested in the impact of the heat on a living being and people are not 0.1 mm thick and that extra thickness has impacts even on the surface. It definitely can have an impact on the numerics in CFAST.

**Comment by preneke** [comment]
This seems to run fine in CFAST 7.7.4. There was a bit of confirmation bias on my part. At 180 s into the simulation the upper layer in the compartment is 150 C and increasing. FED is not calibrated after 1 since that is when the heat, in this case, is deadly. I am going to close this and if there are any other problems please go to the discussion or start a new issue.
