### ISSUE TITLE
CFAST results vs NUREG-1805 FDT for a room with forced ventilation

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#2061]
### Discussed in https://github.com/firemodels/cfast/discussions/2060

<div type='discussions-op-text'>

<sup>Originally posted by **Ranhill** October  1, 2023</sup>
Hello all,

I am trying to model a compartment (10m x 10m x 4m) with 2000kW fire and forced ventilation with rate of 0.2m3/s for supply at floor level and exhaust at ceiling level in CFAST. Compartment is made of concrete (walls are 0.2m thick and ceiling /floor are 0.4m thick). I am looking for the time when the temperature reaches 500C. This does not happen in CFAST as the max temperature is reached by 350s and the value is around 250C, and after that the temperature begins to fall and fire power also decreases. When the compare such time and temperature with NUREG FDT tool (foote et al. method) for forced ventilation, such temperature using FDT for forced ventilation compartment is reached by 2028s. How can there be such a big difference? Or, I am wrong somewhere?

Please guide, thanks!

![6](https://github.com/firemodels/cfast/assets/146167548/64135585-6380-4923-a676-231e850e5961)
![5](https://github.com/firemodels/cfast/assets/146167548/13617e4d-eeb1-40ce-bd0a-214f247f8d82)
![4](https://github.com/firemodels/cfast/assets/146167548/8fc65907-0667-4b69-86b6-e5ffe6a4b302)
![3](https://github.com/firemodels/cfast/assets/146167548/e2f7931e-f67d-42e0-8b27-da3c20dff988)
![2](https://github.com/firemodels/cfast/assets/146167548/d05914ec-e920-4a62-aea0-66af8d771a9f)
![1](https://github.com/firemodels/cfast/assets/146167548/c8032a7b-d9db-429c-8476-449343f2cb0a)
</div>

**Comment by preneke** [comment]
Sorry for the delay. The problem is that the fire is oxygen limited. You have a hermetically sealed compartment with an air flow that is insufficient for the fire. I can run a 200 kW fire but a 500 kW fire is oxygen limited. A 2 MW fire is very oxygen limited. I don't think the NUREG calculations account for oxygen limiting. Keep in mind that the inlet will have the flow limited at 200 Pa above ambient and completely cut off at 300 Pa above ambient. I don't think the solution is to up the cutoff values, by the way. Maybe you can add some leaks.
