### ISSUE TITLE
Wall or corner plumes missing from CFAST

### ISSUE THREAD

**Issue by pimzzff1** [firemodels/cfast#2139]
Hi,

Am I correct to say that CFAST no longer models wall or corner plumes? The TRG still states it does.

Thanks in advance,
Pim

**Comment by preneke** [comment]
You are partially correct. There is no adjustment for wall fires, i.e., fires just against the wall, because experiments did not show any impact. However, corner fires where shown to have an impact and are done the same as they always were. We will have to fix that in the tech ref. Thanks for catching it.

**Comment by preneke** [comment]
Thanks for the thumbs up. I will assume your issues are answered and close this issue.
