### ISSUE TITLE
CFAST GUI does not support negative position offsets

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#430]
The CFAST windows GUI does not support negative numbers for compartment position offsets.

This produces errors in visualization when a manually written CFAST file with negative compartment position offsets is opened in the GUI, which then silently defaults those offsets to 0. If any changes are made to the file from the GUI editor, these 0 values overwrite the negative values, adversely altering the visualization.

This bug is rather esoteric, but I wanted to point it out so that others are aware.

To reproduce this bug, perform the following steps using the supplied code at the bottom of this issue.
1. open the code in the CFAST GUI and run it
2. click 'view' to open the model in smokeview. You will see two compartments side-by-side with a vent between them.
3. (as an example) rename 'Comp 1' to 'test' and save the file
4. run the file and view the smokeview again. The first compartment will have collapsed into the second compartment in the visualization.

This bug occurs because the '-3.6' value on the first COMPA line is replaced by 0 when the file is saved through the GUI (an actual overwrite only occurs if changes have been made, e.g. changing a compartment name).

Code example:
VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,150,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
!!
!!Compartment keywords
!!
COMPA,Comp 1,3.6,2.4,2.4,-3.6,0,0,GYPSUM,GYPSUM,GYPSUM,50,50,50
COMPA,Comp 2,3.6,2.4,2.4,0,0,0,GYPSUM,GYPSUM,GYPSUM,50,50,50
!!
!!Vent keywords
!!
HVENT,1,3,1,0.91,2.1,0,1.8,1,1
HVENT,1,2,1,2.4,2.4,0,0,2,1
!!
!!Fire keywords
!!
!!afire
FIRE,1,1.8,1.2,0,1,TIME,0,0,0,0,afire
CHEMI,3,8,0,0,0,0.3,4.635E+07
TIME,0
HRR,150000
SOOT,0
CO,0
TRACE,0
AREA,0.1024
HEIGH,0

**Comment by rpeacoc** [comment]
This is a long standing design choice in the CFAST model to assume that all compartment positions are positive numbers.  I've updated the CEdit source to correctly produce an error message rather than just resetting the value to zero.  The User's Guide has also been updated to note that these numbers must be positive.  Revision 79a39bf  should have this update to the GUI and documentation.

It's certainly possible to make the code more general so that the position can be negative (and perhaps the simulation time too, but it's far more work that it's worth.  Hopefully, this at least allows users to see that the input needs to be changed.

**Comment by andersonad** [comment]
Thanks for adding an error message. I respect the design choice for usability of the GUI, but wanted to get a word of caution onto the issues list for those adventurous types who build their models from text editors using arbitrary origins.

**Comment by rpeacoc** [comment]
I didn't intend to imply that your issue wasn't significant. This is an important one for users who hand edit the files.  You may want to also post your note at the user's forum https://groups.google.com/forum/#!forum/cfast to give it a wider audience.
