### ISSUE TITLE
CFAST example file fails to run

### ISSUE THREAD

**Issue by jwdevine21** [firemodels/cfast#706]
Hello, 
I tried downloading CFAST 7.2.2 today. I opened the example file that came along with the download to make sure it worked. When I pressed run, it said the CFAST modeling was complete but output no data for me. Does anyone know what is happening? Thanks in advance for your help.

**Comment by rpeacoc** [comment]
I'd look at two things.  First, make sure your computer is set up for U.S. numeric format. See https://www.nist.gov/el/fire-research-division-73300/cfast-faqs#Q6 for details on this.  Second, quite often the example case won't run in the folder it's installed in because you don't have appropriate administrative privileges to folders within the Program Files folder.  If you copy the file to a folder you create in another location, it will often run.

**Comment by rpeacoc** [comment]
It's been more than 2 months since the last post.  If this is still an issue, feel free to reopen and comment.
