### ISSUE TITLE
Radiative heat transfer into structures

### ISSUE THREAD

**Issue by F-J-G** [firemodels/cfast#821]
For the transfer of the radiative flux to other firemodels I want to have the radiative flux into the structure (not out of it). 
My ideas were
I. to take the incident heat flux minus the convective heat flux 
or
II. take the radiative Gauge flux plus sigma times T^4. With T as Gauge tempereature in K. Is my assumption right the Gauge temperatur is equal to the ambient temperature with 20°C=293K?

With my understanding of the model I should get the same radiative heat flux for both ways but when I take 
I. - II.,  
I always get a flux difference of -125 kW.

**Comment by andytamhk168** [comment]
Dear F-J-G,

In CFAST, if you are interested to know the radiative heat flux to a target, you can specific a target and an associated output "incident heat flux" will give you the information you are looking for. Note that, there will be two terms for incident heat flux: 1) front and 2) back.

To address your question for the two expressions you have stated above, we will need to look at each of the terms from the equations closely:

I. "Incident heat flux":
The incident heat flux to a target (front or back) is the sum of radiative heat flux from emission of the surrounding surfaces, fire, and the sooty-gas mixture medium, and convection. Note that, there is a temperature difference (T_gas minus T_target) term in the convection equation and T_target is the temperature of target (front or back) and temperature of the target should not be a fixed value.

II. "Gauge heat flux": (In fact, this is the gauge net heat flux)
The gauge heat flux is the sum of radiative heat flux from emission of the surrounding surfaces, fire, and the sooty-gas mixture medium to the gauge (front or back), convective exchange between the gauge and the medium, and radiative heat loss from the gauge. Note that, the "target" temperature  is different than that of seen from the first expression. Specifically, when you look at the convection term, T_target is now the gauge temperature. Also, you have also notice that there is an extra term --- "radiative heat loss from the gauge" and is a function of gauge temperature as well. 

So, I believe the flux difference should come from the difference of the "target" temperature from the convection term, assuming you make no mistakes to the others. Since your flux difference turns out to be negative, is your gauge temperature in your second expression higher than the "target" temperature in your first expression?

Hope this would help.

Regards,
Andy

**Comment by F-J-G** [comment]
Hello Andy,
thanks for your response. For understanding I used the blog of kristopher Overholt: https://www.koverholt.com/2014/01/heat-fluxes-in-fds/

I want only the radiative heat flux onto the target, **independend of the target material or temperature**. Like q=sigma*T_rad^4

So I think the incident heat flux is not what I'm looking for cause takes the convection into account. But the incident heat flux minus the convective heat flux would be a solution. And this heat flux would be independent of the target temperature and convection so this part can't explain the error.

Maybe it's the assumption of the gauge temperature. I assumed the Gauge temperature in this model is like the ambient temperature = 293K. Do you know if this assumption is right? In this case the flux onto the object should be q=q_gauge+sigma*T_Gauge^4 but with this assumption I get a different result like I wrote before.

Another solution would be the output of the adiabatic surface temperature but I think there is not such a model implemented in CFAST.

Thanks for your help and best regards
Fritz

**Comment by andytamhk168** [comment]
Radiative heat transfer to a particular target (front or back) will be the sum of the following 3 components: 1) emission from the medium (Target Gas Radiative Flux), 2) emission from the surfaces (Target Surface Radiative Flux), and 3) emission from fire(s) (Target Fire Radiative Flux). 

In CFAST, if you have specify a target correct, these three terms will be shown in your <title>_w.csv file.

You may find more detailed information about the methods used to calculate the above three terms from Chapter 5 of CFAST Technical Reference Guides.
